# ì»¤ë°‹ ë¨¹ëŠ” ë±€ ê·¸ë˜í”„ ìƒì„±ì„ ìœ„í•œ GitHub ActionğŸ

name: Generate Snake

# Actionì´ ì–¸ì œ êµ¬ë™ë ì§€ ê²°ì •

on:
  schedule:
    # 6ì‹œê°„ë§ˆë‹¤ í•œ ë²ˆ(ìˆ˜ì • ê°€ëŠ¥)
    - cron: "0 */6 * * *"

  # ìë™ìœ¼ë¡œ Actionì´ ì‹¤í–‰ë˜ë„ë¡ í•¨
  workflow_dispatch:

runs:
  using: docker
  image: docker://platane/snk@sha256:dcb351bdad223f2a2161fa5d6e3c9102e6ebe9fbde99a10fa3bf443d69f61a0f

inputs:
  github_user_name:
    description: JessiJung
    required: true
  outputs:
    required: false
    default: null
    description: |
      list of files to generate.
      one file per line. Each output can be customized with options as query string.
       supported query string options:
      - palette:      A preset of color, one of [github, github-dark, github-light]
      - color_snake:  Color of the snake
      - color_dots:   Coma separated list of dots color. 
                      The first one is 0 contribution, then it goes from the low contribution to the highest.
                      Exactly 5 colors are expected.
      example:
        outputs: |
          dark.svg?palette=github-dark&color_snake=blue
          light.svg?color_snake=#7845ab
          ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
